DROP TABLE BROADCAST;
DROP TABLE REPORT;
DROP TABLE FORUM_MSG;
DROP TABLE FORUM_ART;
DROP TABLE AUTH;
DROP TABLE FUN;
DROP TABLE EMP;
DROP TABLE MENU_DISH;
DROP TABLE MENU_ORDER;
DROP TABLE MENU;
DROP TABLE FEST_ORDER_DETAIL;
DROP TABLE FEST_ORDER;
DROP TABLE FEST_DISH;
DROP TABLE FEST_MENU;
DROP TABLE CHEF_OD_DETAIL;
DROP TABLE CHEF_ORDER;
DROP TABLE FOOD_OR_DETAIL;
DROP TABLE FOOD_ORDER;
DROP TABLE FOOD_MALL;
DROP TABLE FAV_FD_SUP;
DROP TABLE AD;
DROP TABLE FOOD_SUP;
DROP TABLE DISH_FOOD;
DROP TABLE FOOD;
DROP TABLE CHEF_DISH;
DROP TABLE DISH;
DROP TABLE CHEF_SCH;
DROP TABLE FAV_CHEF;
DROP TABLE CHEF;
DROP TABLE CUST;

DROP SEQUENCE CUST_SEQ;
DROP SEQUENCE MENU_SEQ;
DROP SEQUENCE BROADCAST_SEQ;
DROP SEQUENCE CHEF_SEQ;
DROP SEQUENCE FOOD_SEQ;
DROP SEQUENCE FOOD_SUP_SEQ;
DROP SEQUENCE FOOD_ORDER_SEQ;
DROP SEQUENCE FAV_CHEF_SEQ;
DROP SEQUENCE CHEF_ORDER_SEQ;
DROP SEQUENCE CHEF_OD_DETAIL_SEQ;

ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy-mm-dd';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'yyyy-mm-dd hh24:mi:ss';
SET DEFINE OFF;

------------------------------------------------------------------
--建立表格:顧客--
CREATE TABLE CUST (
 CUST_ID                 VARCHAR2(6)   NOT NULL,
 CUST_ACC                VARCHAR2(15)  NOT NULL,
 CUST_PWD                VARCHAR2(15)  NOT NULL,
 CUST_NAME               VARCHAR2(30)  NOT NULL,
 CUST_SEX                VARCHAR2(1)   NOT NULL,
 CUST_TEL                VARCHAR2(20)    NOT NULL,
 CUST_ADDR               VARCHAR2(200) NOT NULL,
 CUST_PID                CHAR(10)      NOT NULL,
 CUST_MAIL               VARCHAR2(30)  NOT NULL,
 CUST_BRD                DATE,
 CUST_REG                DATE          NOT NULL,
 CUST_PIC                BLOB,
 CUST_STATUS             VARCHAR2(2)     NOT NULL,
 CUST_NINAME             VARCHAR2(30)  NOT NULL,
 PRIMARY KEY (CUST_ID),
 UNIQUE (CUST_ACC)
);

CREATE SEQUENCE CUST_SEQ
MINVALUE 1
NOMAXVALUE 
START WITH 1
INCREMENT BY 1;

--SELECT CUST_SEQ.NEXTVAL FROM CUST;

Insert into CUST (CUST_ID,CUST_ACC,CUST_PWD,CUST_NAME,CUST_SEX,CUST_TEL,CUST_ADDR,CUST_PID,CUST_MAIL,CUST_BRD,CUST_REG,CUST_STATUS,CUST_NINAME) 
values ('C00001','acust','234561','David','1','0910889862','桃園市中壢區中大路300號','H123456789','david123@yahoo.com',to_date('2019-02-01','YYYY-MM-DD'),to_date('2019-02-01','YYYY-MM-DD'),'0','seafood');
Insert into CUST (CUST_ID,CUST_ACC,CUST_PWD,CUST_NAME,CUST_SEX,CUST_TEL,CUST_ADDR,CUST_PID,CUST_MAIL,CUST_BRD,CUST_REG,CUST_STATUS,CUST_NINAME)
values ('C00002','custa2','123456','Peter','1','0910889866','桃園市中壢區中大路301號','A123557799','peter123@yahoo.com',to_date('2000-01-01','YYYY-MM-DD'),to_date('2019-02-06','YYYY-MM-DD'),'0','Peterseafood');
Insert into CUST (CUST_ID,CUST_ACC,CUST_PWD,CUST_NAME,CUST_SEX,CUST_TEL,CUST_ADDR,CUST_PID,CUST_MAIL,CUST_BRD,CUST_REG,CUST_STATUS,CUST_NINAME)
values ('C00003','custa3','123456','Amy','0','0910889867','桃園市中壢區中大路302號','A223456789','amy123@yahoo.com',to_date('1989-01-01','YYYY-MM-DD'),to_date('2019-02-01','YYYY-MM-DD'),'0','Amy');
Insert into CUST (CUST_ID,CUST_ACC,CUST_PWD,CUST_NAME,CUST_SEX,CUST_TEL,CUST_ADDR,CUST_PID,CUST_MAIL,CUST_BRD,CUST_REG,CUST_STATUS,CUST_NINAME) 
values ('C00004','cookb1','123456','Tom','1','0910889869','桃園市中壢區中大路305號','B124456789','tom123@yahoo.com',to_date('1990-01-01','YYYY-MM-DD'),to_date('2019-02-01','YYYY-MM-DD'),'0','Tomcat');
Insert into CUST (CUST_ID,CUST_ACC,CUST_PWD,CUST_NAME,CUST_SEX,CUST_TEL,CUST_ADDR,CUST_PID,CUST_MAIL,CUST_BRD,CUST_REG,CUST_STATUS,CUST_NINAME) 
values ('C00005','foodsupc2','123456','Candy','0','0910889864','桃園市中壢區中大路306號','C223456788','candy123@yahoo.com',to_date('1980-02-01'),to_date('2019-02-08'),'0','Candyshop');

INSERT INTO CUST (CUST_ID,CUST_ACC,CUST_PWD,CUST_NAME,CUST_SEX,CUST_TEL,CUST_ADDR,CUST_PID,CUST_MAIL,CUST_BRD,CUST_REG,CUST_STATUS,CUST_NINAME) 
VALUES ('T00001','CUST','123456','AAA','1','0987654321','桃園市中壢區1號','A123456789','TEST_01@GMAIL.COM',TO_DATE('2000-01-01','YYYY-MM-DD'),TO_DATE('2019-02-11','YYYY-MM-DD'),'0','DAVID_01');

INSERT INTO CUST (CUST_ID,CUST_ACC,CUST_PWD,CUST_NAME,CUST_SEX,CUST_TEL,CUST_ADDR,CUST_PID,CUST_MAIL,CUST_BRD,CUST_REG,CUST_STATUS,CUST_NINAME) 
VALUES ('T00002','CHEF','123456','BBB','1','0987654322','桃園市中壢區2號','B223456789','TEST_02@GMAIL.COM',TO_DATE('2000-02-02','YYYY-MM-DD'),TO_DATE('2019-02-11','YYYY-MM-DD'),'0','DAVID_02');

INSERT INTO CUST (CUST_ID,CUST_ACC,CUST_PWD,CUST_NAME,CUST_SEX,CUST_TEL,CUST_ADDR,CUST_PID,CUST_MAIL,CUST_BRD,CUST_REG,CUST_STATUS,CUST_NINAME) 
VALUES ('T00003','FOOD_SUP','123456','CCC','1','0987654323','桃園市中壢區3號','C323456789','TEST_03@GMAIL.COM',TO_DATE('2000-03-03','YYYY-MM-DD'),TO_DATE('2019-02-11','YYYY-MM-DD'),'0','DAVID_03');



------------------------------------------------------------------
--建立表格:主廚--
CREATE TABLE CHEF (
 CHEF_ID                  VARCHAR2(6)    NOT NULL,
 CHEF_AREA                CHAR(1)        NOT NULL,
 CHEF_STATUS              NUMBER(1)      NOT NULL,
 CHEF_CHANNEL             VARCHAR2(100),
 CHEF_RESUME              VARCHAR2(1500) NOT NULL,
 CHEF_LICENSE             BLOB           NOT NULL,
 CONSTRAINT CHEF_FK FOREIGN KEY (CHEF_ID) REFERENCES CUST (CUST_ID),
 PRIMARY KEY (CHEF_ID) 
);
CREATE SEQUENCE CHEF_SEQ
MINVALUE 1
NOMAXVALUE 
START WITH 1
INCREMENT BY 1;

INSERT INTO CHEF(CHEF_ID,CHEF_AREA,CHEF_STATUS,CHEF_CHANNEL,CHEF_RESUME,CHEF_LICENSE)
VALUES('C02121','0',0,'https://www.youtube.com/channel/UC_XRq7JriAORvDe1lI1RAsA','女主角，趙瑜與梅香的獨生女，原為14歲，燒賣對決過後是15歲。容貌與過世的母親梅香極為相似。',hextoraw('0'));

--(REMOVE CHEF_LICENSE NOT NULL)--
INSERT INTO CHEF (CHEF_ID,CHEF_AREA,CHEF_STATUS,CHEF_CHANNEL,CHEF_RESUME,CHEF_LICENSE)
VALUES ('T00003','5',1,'WWW.YOUTUBE.COM','BIG_MASTER',hextoraw('0000'));
------------------------------------------------------------------
--建立表格:喜愛主廚--
CREATE TABLE FAV_CHEF (
 CUST_ID                  VARCHAR2(6)    NOT NULL,
 CHEF_ID                  VARCHAR2(6)    NOT NULL,
 CONSTRAINT FAV_CHEF_FK1 FOREIGN KEY (CUST_ID) REFERENCES CUST (CUST_ID),
 CONSTRAINT FAV_CHEF_FK2 FOREIGN KEY (CHEF_ID) REFERENCES CHEF (CHEF_ID),
 CONSTRAINT FAV_CHEF_PK  PRIMARY KEY (CUST_ID,CHEF_ID)
);

INSERT INTO FAV_CHEF(CUST_ID,CHEF_ID)
VALUES('a00001','T00003');
INSERT INTO FAV_CHEF(CUST_ID,CHEF_ID)
VALUES('a00002','T00003');
INSERT INTO FAV_CHEF(CUST_ID,CHEF_ID)
VALUES('a00003','T00003');
INSERT INTO FAV_CHEF(CUST_ID,CHEF_ID)
VALUES('b00001','T00003');
INSERT INTO FAV_CHEF(CUST_ID,CHEF_ID)
VALUES('c00002','T00003');



-----------------------------------------------------------------------------------------------------------------------------------
--建立表格:主廚排程--
CREATE TABLE CHEF_SCH (
 CHEF_SCH_DATE            DATE           NOT NULL,
 CHEF_ID                  VARCHAR2(6)    NOT NULL,
 CHEF_SCH_STATUS          NUMBER(1)      NOT NULL,
 CONSTRAINT CHEF_SCH_FK FOREIGN KEY (CHEF_ID) REFERENCES CUST (CUST_ID),
 PRIMARY KEY (CHEF_SCH_DATE,CHEF_ID)
);
INSERT INTO CHEF_SCH (CHEF_SCH_DATE,CHEF_ID,CHEF_SCH_STATUS)
VALUES (TO_DATE('2019-02-11','YYYY-MM-DD'),'T00002',0);

------------------------------------------------------------------
--建立表格:菜色--
CREATE TABLE DISH (
 DISH_ID                  VARCHAR2(6)    NOT NULL,
 DISH_NAME                VARCHAR2(30)   NOT NULL,
 DISH_STATUS              NUMBER(1)      NOT NULL,
 DISH_PIC                 BLOB           NOT NULL,
 DISH_RESUME              VARCHAR2(1500) NOT NULL,
 DISH_PRICE               NUMBER(6),
 PRIMARY KEY (DISH_ID)
);
--(REMOVE DISH_PIC NOT NULL)--
INSERT INTO DISH (DISH_ID,DISH_NAME,DISH_STATUS,DISH_PIC,DISH_RESUME,DISH_PRICE)
VALUES ('D00001','BIG_SEAFOOD',1,hextoraw('111111'),'VERY BIG',88);

INSERT INTO DISH VALUES (80001,'御膳桂丁雞湯','1',NULL,'上湯採老母雞、豬腳、金華火腿慢火精熬，再佐以干貝、竹笙及新鮮菜捲等食材，鮮甜一口難忘。','250');
INSERT INTO DISH VALUES (80002,'現煎天使紅蝦','1',NULL,'天使紅蝦肉質厚實不粉柴，簡單以椒鹽、蒜香奶油調味，鹹香美味，搭配松露洋芋泥佐巴薩米克醋與黃芥末，就像品嚐一道高級鐵板料理。','250');
INSERT INTO DISH VALUES (80003,'火烤甜白蝦','1',NULL,'特選甜白蝦輕抹薄鹽，以中火炙烤，蝦肉鮮甜緊實，吃得到原味。','250');
INSERT INTO DISH VALUES (80004,'和牛握壽司','1',NULL,'選自最佳種源的澳洲和牛，特殊大理石油花，簡單炙燒逼出濃郁香氣，多款配料點綴提味，一貫接一貫不停手！','250');
INSERT INTO DISH VALUES (80005,'嫩煎嫩貝','1',NULL,'嚴選日本北海道純淨海域生食級干貝，雙面略煎上色，搭配松露醬品嚐，口口都能感受到大海的鮮甜滋味！','250');
INSERT INTO DISH VALUES (80006,'法式羊肩排','1',NULL,'嚴選紐西蘭小羔羊羊肩，肉質鮮嫩細緻，無羊羶味；以百里香、迷迭香油封過夜，鐵板現煎創造外酥內軟的絕佳口感。','250');
INSERT INTO DISH VALUES (80007,'爐烤肋眼牛排','1',NULL,'採用美國特選級肋眼，以香料、胡椒醃漬入味，再與多種蔬果一起爐烤至5分熟，肉質軟嫩細緻，香氣撲鼻。','250');
INSERT INTO DISH VALUES (80008,'焦糖烤布蕾','1',NULL,'冬天最適合吃熱熱的烤布蕾，脆脆的焦糖搭配綿密的烤布蕾，滑順的口感讓人忍不住一口接一口，冰涼吃也很好吃喔！','250');
INSERT INTO DISH VALUES (80009,'黑麻油雞麵線','1',NULL,'以三十多年歷史純正北港黑麻油煸炒薑片，再加入桂丁雞腿肉、麻油煎蛋及當歸等食材，香氣令人垂涎。','250');
INSERT INTO DISH VALUES (80010,'焗烤生蠔','1',NULL,'來自日本優質海域，以胡椒、清酒、檸檬汁調味，搭配奶油白醬與雙色起司焗烤，奶香濃郁鮮甜滿溢！','250');


------------------------------------------------------------------
--建立表格:主廚擅長菜色--
CREATE TABLE CHEF_DISH (
 CHEF_ID                  VARCHAR2(6)   NOT NULL,
 DISH_ID                  VARCHAR2(6)   NOT NULL,
 CHEF_DISH_STATUS         NUMBER(1)     NOT NULL,
 CONSTRAINT CHEF_DISH_FK1 FOREIGN KEY (DISH_ID) REFERENCES DISH (DISH_ID), 
 CONSTRAINT CHEF_DISH_FK2 FOREIGN KEY (CHEF_ID) REFERENCES CHEF (CHEF_ID),
 CONSTRAINT CHEF_DISH_PK  PRIMARY KEY (CHEF_ID,DISH_ID)
);
INSERT INTO CHEF_DISH (CHEF_ID,DISH_ID,CHEF_DISH_STATUS)
VALUES ('T00002','D00001',1);
------------------------------------------------------------------
--建立表格:食材--
CREATE TABLE FOOD (
 FOOD_ID                  VARCHAR2(6)   NOT NULL,
 FOOD_NAME                VARCHAR2(30)  NOT NULL,
 PRIMARY KEY (FOOD_ID)
);

-----------------------食材自動編號器-------------------------------
CREATE SEQUENCE FOOD_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-------------------------------食材資料----------------------------------------------------------------
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0') , '五穀米');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '波士頓龍蝦');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '草蝦');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '芹菜');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '菠菜');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '法國松露');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '鵝肝');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '牛肝菌');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '雞蛋');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '豬尾冬骨');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '豬腳');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '豬肚');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '豬肝');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '豬心');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '松阪豬肉');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '五花肉');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '黑木耳');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '銀耳');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '枸杞');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '紅棗');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '核桃');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '牛臉頰肉');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '牛舌');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '牛頸肉');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '牛板腱肉');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0'), '牛翼板肉');
INSERT INTO FOOD (FOOD_ID, FOOD_NAME) VALUES ('F'||LPAD(TO_CHAR (FOOD_SEQ.NEXTVAL), 5, '0') , '德國豬腳');

------------------------------------------------------------------
--建立表格:菜色使用食材--
CREATE TABLE DISH_FOOD (
 DISH_ID                  VARCHAR2(6)   NOT NULL,
 FOOD_ID                  VARCHAR2(6)   NOT NULL,
 DISH_F_QTY               NUMBER(4)     NOT NULL,
 DISH_F_UNIT              VARCHAR2(4),
 CONSTRAINT DISH_FOOD_FK1  FOREIGN KEY (DISH_ID) REFERENCES DISH (DISH_ID),
 CONSTRAINT DISH_FOOD_FK2  FOREIGN KEY (FOOD_ID) REFERENCES FOOD (FOOD_ID),
 CONSTRAINT DISH_FOOD_PK   PRIMARY KEY (DISH_ID,FOOD_ID)
);

------------------------------------------------------------------
--建立表格:食材供應商--
CREATE TABLE FOOD_SUP (
 FOOD_SUP_ID                VARCHAR2(6)   NOT NULL,
 FOOD_SUP_NAME              VARCHAR2(30)  NOT NULL,
 FOOD_SUP_TEL               NUMBER(20)    NOT NULL,
 FOOD_SUP_ADDR              VARCHAR2(200) NOT NULL,
 FOOD_SUP_EMAIL             VARCHAR2(30)  NOT NULL,
 FOOD_SUP_REG               DATE          NOT NULL,
 FOOD_SUP_STATUS            NUMBER(1)     NOT NULL,
 FOOD_SUP_PIC               BLOB ,
 FOOD_SUP_RESUME            VARCHAR2(1500),
 FOOD_SUP_LICENSE           BLOB          NOT NULL,
 CONSTRAINT FOOD_SUP_FK FOREIGN KEY (FOOD_SUP_ID) REFERENCES CUST (CUST_ID),
 PRIMARY KEY (FOOD_SUP_ID) 
);
CREATE SEQUENCE FOOD_SUP_SEQ
MINVALUE 1
NOMAXVALUE 
START WITH 1
INCREMENT BY 1;

INSERT INTO FOOD_SUP(FOOD_SUP_ID,FOOD_SUP_NAME,FOOD_SUP_TEL,FOOD_SUP_ADDR,FOOD_SUP_EMAIL,FOOD_SUP_REG,FOOD_SUP_STATUS,FOOD_SUP_RESUME,FOOD_SUP_LICENSE)
VALUES('C00005','Candyshop',022345678,'台北市萬華區三水街70號','Taipei@gmail.com',SYSDATE,0,'新富市場，又稱東三水街市場，是一座位在臺北市的傳統市場。',hextoraw('111111'));

--(REMOVE FOOD_SUP_LICENSE NOT NULL)--
INSERT INTO FOOD_SUP (FOOD_SUP_ID,FOOD_SUP_NAME,FOOD_SUP_TEL,FOOD_SUP_ADDR,FOOD_SUP_EMAIL,FOOD_SUP_REG,FOOD_SUP_STATUS,FOOD_SUP_LICENSE) 
VALUES ('T00003','DAVID_SEAFOOD','0988888888','新北市汐止區發財路88號','DAVID.SEAFOOD@GMAIL.COM',TO_DATE('2019-02-11','YYYY-MM-DD'),1,hextoraw('111111'));
------------------------------------------------------------------
--建立表格:廣告--
CREATE TABLE AD (
 AD_ID                    VARCHAR2(8)      NOT NULL,
 AD_STATUS                VARCHAR2(2)      NOT NULL,
 AD_START                 TIMESTAMP        NOT NULL,
 AD_END                   TIMESTAMP        NOT NULL,
 AD_TYPE                  VARCHAR2(2)      NOT NULL,
 AD_TITLE                 VARCHAR2(30)     NOT NULL,
 AD_CON                   CLOB             NOT NULL,
 FOOD_SUP_ID              VARCHAR2(6),
 CONSTRAINT AD_FK FOREIGN KEY (FOOD_SUP_ID) REFERENCES FOOD_SUP (FOOD_SUP_ID),
 PRIMARY KEY (AD_ID) 
);
REM INSERTING into AD
SET DEFINE OFF;
Insert into AD (AD_ID,AD_STATUS,AD_START,AD_END,AD_TYPE,AD_TITLE,AD_CON,FOOD_SUP_ID) 
values ('AD000001','1',to_timestamp('2019-02-13 04.35.21'),to_timestamp('2019-04-18 12.32.29'),'1','阿基師春節限定','阿基師特選寶島復古料理四天王，「滑溜溜佛跳牆」「五花大綁肉」「溫煮牛肉湯」「功夫老雞煲」 讓你吃得巧，吃到飽～',null);
Insert into AD (AD_ID,AD_STATUS,AD_START,AD_END,AD_TYPE,AD_TITLE,AD_CON,FOOD_SUP_ID)
values ('AD000002','1',to_timestamp('2019-02-28 04.42.39'),to_timestamp('2019-04-14 04.42.44'),'2','帝王感蟹季','在遙遠南極的海下，科學家曾發現超過100萬只巨型帝王蟹。它們是石蟹科的甲殼類，不是真正的螃蟹。這種生物主要分布在寒冷的海域， 素有蟹中之王的美譽，聽了是不是都流口水了?',null);
Insert into AD (AD_ID,AD_STATUS,AD_START,AD_END,AD_TYPE,AD_TITLE,AD_CON,FOOD_SUP_ID)
values ('AD000003','1',to_timestamp('2019-02-27 08.57.09'),to_timestamp('2019-04-24 08.57.15'),'0','人氣日本和牛','找日本人問何謂人氣「和牛」，可能沒幾個日本人能回答你的問題。這篇要告訴你何謂人氣和牛，又，哪裡可以吃到這些知名和牛呢？',null);
------------------------------------------------------------------
--建立表格:喜愛食材供應商--
CREATE TABLE FAV_FD_SUP (
 CHEF_ID                   VARCHAR2(6)    NOT NULL,
 FOOD_SUP_ID               VARCHAR2(6)    NOT NULL,
 FAV_FD_SUP_NOTE           VARCHAR2(300),
 FAV_FD_SUP_NUM            NUMBER(2),
 CONSTRAINT FAV_FD_SUP_FK1 FOREIGN KEY (CHEF_ID)     REFERENCES CHEF (CHEF_ID),
 CONSTRAINT FAV_FD_SUP_FK2 FOREIGN KEY (FOOD_SUP_ID) REFERENCES FOOD_SUP (FOOD_SUP_ID),
 CONSTRAINT FAV_FD_SUP_PK  PRIMARY KEY (CHEF_ID,FOOD_SUP_ID)
);
INSERT INTO FAV_FD_SUP (CHEF_ID,FOOD_SUP_ID,FAV_FD_SUP_NOTE,FAV_FD_SUP_NUM)
VALUES ('T00002','T00003','THE BEST',1);
------------------------------------------------------------------
 
--建立表格:商城食材--
CREATE TABLE FOOD_MALL (
 FOOD_SUP_ID                VARCHAR2(6)   NOT NULL,
 FOOD_ID                    VARCHAR2(6)   NOT NULL,
 FOOD_M_NAME                VARCHAR2(30)  NOT NULL,
 FOOD_M_STATUS              VARCHAR2(2)     NOT NULL,
 FOOD_M_PRICE               NUMBER(6)     NOT NULL,
 FOOD_M_UNIT                VARCHAR2(8)   NOT NULL,
 FOOD_M_PLACE               VARCHAR2(30)  NOT NULL,
 FOOD_M_PIC                 BLOB          NOT NULL,
 FOOD_M_RESUME              VARCHAR2(1500),
 FOOD_M_RATE                NUMBER(1),
 CONSTRAINT FOOD_MALL_FK1 FOREIGN KEY (FOOD_SUP_ID) REFERENCES FOOD_SUP (FOOD_SUP_ID),
 CONSTRAINT FOOD_MALL_FK2 FOREIGN KEY (FOOD_ID)     REFERENCES FOOD (FOOD_ID),
 CONSTRAINT FOOD_MALL_PK  PRIMARY KEY (FOOD_SUP_ID,FOOD_ID) 
);

INSERT INTO FOOD_MALL(FOOD_SUP_ID,FOOD_ID,FOOD_M_NAME,FOOD_M_STATUS,FOOD_M_PRICE,FOOD_M_UNIT,FOOD_M_PLACE,FOOD_M_PIC,FOOD_M_RESUME,FOOD_M_RATE)
VALUES('T00003','F00001','123',1,800,'54','123',hextoraw('13'),'555',1);

------------------------------------------------------------------
--建立表格:食神嚴選食材訂單--
CREATE TABLE FOOD_ORDER (
 FOOD_OR_ID                VARCHAR2(6)    NOT NULL,
 FOOD_OR_STATUS            NUMBER(1)      NOT NULL, 
 FOOD_OR_START             DATE           NOT NULL,
 FOOD_OR_SEND              DATE           NOT NULL,
 FOOD_OR_RCV               DATE,
 FOOD_OR_END               DATE,
 FOOD_OR_NAME              VARCHAR2(30)   NOT NULL,
 FOOD_OR_ADDR              VARCHAR2(200)  NOT NULL,
 FOOD_OR_TEL               NUMBER(10)     NOT NULL,
 CUST_ID                   VARCHAR2(6)    NOT NULL,
 CONSTRAINT FOOD_ORDER_FK FOREIGN KEY (CUST_ID) REFERENCES CUST (CUST_ID),
 PRIMARY KEY (FOOD_OR_ID) 
);


------------------------------------------------------------------
--建立表格:食神嚴選食材訂單明細--
CREATE TABLE FOOD_OR_DETAIL (
 FOOD_OR_ID                VARCHAR2(6)   NOT NULL,
 FOOD_SUP_ID               VARCHAR2(6)   NOT NULL,
 FOOD_ID                   VARCHAR2(6)   NOT NULL,
 FOOD_OD_QTY               NUMBER(4)     NOT NULL,
 FOOD_OD_STOTAL            NUMBER(7)     NOT NULL,
 FOOD_OD_RATE              NUMBER(1),
 FOOD_OD_MSG               VARCHAR2(300),
 CONSTRAINT FOOD_OR_DETAIL_FK1 FOREIGN KEY (FOOD_OR_ID)          REFERENCES FOOD_ORDER (FOOD_OR_ID),
 CONSTRAINT FOOD_OR_DETAIL_FK2 FOREIGN KEY (FOOD_SUP_ID,FOOD_ID) REFERENCES FOOD_MALL (FOOD_SUP_ID,FOOD_ID),
 CONSTRAINT FOOD_OR_DETAIL_PK  PRIMARY KEY (FOOD_OR_ID,FOOD_SUP_ID,FOOD_ID) 
);

------------------------------------------------------------------
--建立表格:主廚食材訂單--
CREATE TABLE CHEF_ORDER (
 CHEF_OR_ID                 VARCHAR2(17)  NOT NULL,
 CHEF_OR_STATUS             VARCHAR2(2)   NOT NULL,
 CHEF_OR_START              DATE          NOT NULL,
 CHEF_OR_SEND               DATE          NOT NULL,
 CHEF_OR_RCV                DATE,
 CHEF_OR_END                DATE,
 CHEF_OR_NAME               VARCHAR2(30)  NOT NULL,
 CHEF_OR_ADDR               VARCHAR2(200) NOT NULL,
 CHEF_OR_TEL                NUMBER(10)    NOT NULL,
 CHEF_ID                    VARCHAR2(6)   NOT NULL,
 CONSTRAINT CHEF_ORDER_FK FOREIGN KEY (CHEF_ID) REFERENCES CHEF (CHEF_ID),
 PRIMARY KEY (CHEF_OR_ID)
);

DROP SEQUENCE CHEF_ORDER_SEQ;

CREATE SEQUENCE CHEF_ORDER_SEQ
NOMAXVALUE 
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO CHEF_ORDER(CHEF_OR_ID,CHEF_OR_STATUS,CHEF_OR_START,CHEF_OR_SEND,CHEF_OR_NAME,CHEF_OR_ADDR,CHEF_OR_TEL,CHEF_ID)
VALUES('CF20190212-100001',0,SYSDATE,TO_DATE('2019-02-11'),'David','桃園市中壢區中大路300號',32885252,'T00003');
INSERT INTO CHEF_ORDER(CHEF_OR_ID,CHEF_OR_STATUS,CHEF_OR_START,CHEF_OR_SEND,CHEF_OR_NAME,CHEF_OR_ADDR,CHEF_OR_TEL,CHEF_ID)
VALUES('CF20190212-100002',0,SYSDATE,TO_DATE('2019-02-11'),'Peter','桃園市中壢區中大路300號',32885252,'T00003');
INSERT INTO CHEF_ORDER(CHEF_OR_ID,CHEF_OR_STATUS,CHEF_OR_START,CHEF_OR_SEND,CHEF_OR_NAME,CHEF_OR_ADDR,CHEF_OR_TEL,CHEF_ID)
VALUES('CF20190212-100003',0,SYSDATE,TO_DATE('2019-02-11'),'Amy','桃園市中壢區中大路300號',32885252,'T00003');
INSERT INTO CHEF_ORDER(CHEF_OR_ID,CHEF_OR_STATUS,CHEF_OR_START,CHEF_OR_SEND,CHEF_OR_NAME,CHEF_OR_ADDR,CHEF_OR_TEL,CHEF_ID)
VALUES('CF20190212-100004',0,SYSDATE,TO_DATE('2019-02-11'),'Tom','桃園市中壢區中大路300號',32885252,'T00003');
INSERT INTO CHEF_ORDER(CHEF_OR_ID,CHEF_OR_STATUS,CHEF_OR_START,CHEF_OR_SEND,CHEF_OR_NAME,CHEF_OR_ADDR,CHEF_OR_TEL,CHEF_ID)
VALUES('CF20190212-100005',0,SYSDATE,TO_DATE('2019-02-11'),'Candy','桃園市中壢區中大路300號',32885252,'T00003');

--INSERT INTO CHEF_ORDER(CHEF_OR_ID,CHEF_OR_STATUS,CHEF_OR_START,CHEF_OR_SEND,CHEF_OR_NAME,CHEF_OR_ADDR,CHEF_OR_TEL,CHEF_ID)
--VALUES('CF'||TO_CHAR(SYSDATE,'YYYYMMDD')||'-'||LPAD((CHEF_ORDER_SEQ.NEXTVAL),6,'0'),0,SYSDATE,TO_DATE('2019-02-11'),'David','桃園市中壢區中大路300號',32885252,'T00003');
-----------------------------------------------------------------------------------------------------------------------------------
--建立表格:主廚食材訂單明細--
CREATE TABLE CHEF_OD_DETAIL (
 CHEF_OR_ID                  VARCHAR2(17)   NOT NULL,
 FOOD_SUP_ID                 VARCHAR2(6)    NOT NULL,
 FOOD_ID                     VARCHAR2(6)    NOT NULL,
 CHEF_OD_QTY                 NUMBER(4)      NOT NULL,
 CHEF_OD_STOTAL              NUMBER(7)      NOT NULL,
 CONSTRAINT CHEF_OD_DETAIL_FK1 FOREIGN KEY (CHEF_OR_ID)          REFERENCES CHEF_ORDER (CHEF_OR_ID),
 CONSTRAINT CHEF_OD_DETAIL_FK2 FOREIGN KEY (FOOD_SUP_ID,FOOD_ID) REFERENCES FOOD_MALL (FOOD_SUP_ID,FOOD_ID),
 CONSTRAINT CHEF_OD_DETAIL_PK  PRIMARY KEY (CHEF_OR_ID,FOOD_SUP_ID,FOOD_ID)
);

--DROP SEQUENCE CHEF_OD_DETAIL_SEQ;

CREATE SEQUENCE CHEF_OD_DETAIL_SEQ
NOMAXVALUE 
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO CHEF_OD_DETAIL(CHEF_OR_ID,FOOD_SUP_ID,FOOD_ID,CHEF_OD_QTY,CHEF_OD_STOTAL)
VALUES('CF20190212-100001','T00003','F00001',1,199);
-----------------------------------------------------------------------------------------------------------------------------------
--建立表格:節慶主題料理--
CREATE TABLE FEST_MENU (
 FEST_M_ID               VARCHAR2(6)          NOT NULL,
 FEST_M_NAME             VARCHAR2(30)         NOT NULL,
 FEST_M_QTY              NUMBER(4)            NOT NULL,
 FEST_M_START            DATE                 NOT NULL,
 FEST_M_END              DATE                 NOT NULL,
 FEST_M_PIC              BLOB,
 FEST_M_RESUME           VARCHAR2(1500),
 FEST_M_SEND             DATE                 NOT NULL,
 FEST_M_STATUS           NUMBER(1)            NOT NULL,
 FEST_M_KIND             VARCHAR2(30)         NOT NULL,
 CHEF_ID                 VARCHAR2(6)          NOT NULL,
 CONSTRAINT FEST_MENU_FK FOREIGN KEY (CHEF_ID) REFERENCES CHEF (CHEF_ID),
 PRIMARY KEY (FEST_M_ID)
);

------------------------------------------------------------------
--建立表格:節慶主題料理菜色--
CREATE TABLE FEST_DISH(
 DISH_ID		         VARCHAR2(6)         NOT NULL,
 FEST_M_ID	             VARCHAR2(6)         NOT NULL,
 CONSTRAINT FEST_DISH_FK1 FOREIGN KEY(DISH_ID)   REFERENCES DISH (DISH_ID),
 CONSTRAINT FEST_DISH_FK2 FOREIGN KEY(FEST_M_ID) REFERENCES FEST_MENU (FEST_M_ID),
 CONSTRAINT FEST_DISH_PK  PRIMARY KEY (DISH_ID,FEST_M_ID)
);

------------------------------------------------------------------
--建立表格:節慶主題料理訂單--
CREATE TABLE FEST_ORDER(
 FEST_OR_ID		        VARCHAR2(6)     NOT NULL,	
 FEST_OR_STATUS		    NUMBER(1)       NOT NULL,
 FEST_OR_PRICE		    NUMBER(7)       NOT NULL,
 FEST_OR_START		    DATE            NOT NULL,
 FEST_OR_SEND		    DATE            NOT NULL,
 FEST_OR_END		   	DATE            NOT NULL,
 FEST_OR_DISC		    VARCHAR2(30),
 CUST_ID			    VARCHAR2(6)     NOT NULL,
 CONSTRAINT FEST_ORDER_FK FOREIGN KEY (CUST_ID) REFERENCES CUST (CUST_ID),
 PRIMARY KEY (FEST_OR_ID)
);

------------------------------------------------------------------
--建立表格:節慶主題料理訂單明細--
CREATE TABLE FEST_ORDER_DETAIL(
 FEST_OR_ID	            VARCHAR2(6)    NOT NULL,
 FEST_M_ID	            VARCHAR2(6)    NOT NULL,
 FEST_OR_RATE	   	    NUMBER(1),  
 FEST_OR_MSG	   	    VARCHAR2(300),
 FEST_OR_QTY		    NUMBER(4)      NOT NULL,
 FEST_OR_STOTAL	        NUMBER(8)      NOT NULL,
 CONSTRAINT FEST_ORDER_DETAIL_FK1 FOREIGN KEY (FEST_M_ID)  REFERENCES FEST_MENU (FEST_M_ID),
 CONSTRAINT FEST_ORDER_DETAIL_FK2 FOREIGN KEY (FEST_OR_ID) REFERENCES FEST_ORDER (FEST_OR_ID),
 CONSTRAINT FEST_ORDER_DETAIL_PK  PRIMARY KEY (FEST_OR_ID,FEST_M_ID)
);

---------------------------------------------------------------
--建立表格:嚴選套餐--
CREATE TABLE MENU(
 MENU_ID		          VARCHAR2(6)    NOT NULL,
 MENU_NAME	              VARCHAR2 (30)  NOT NULL,
 MENU_RESUME		      CLOB,
 MENU_PIC	              BLOB,
 MENU_STATUS	          VARCHAR2(2)    NOT NULL,
 MENU_PRICE		          NUMBER(6)      NOT NULL,
 PRIMARY KEY (MENU_ID)
);

--DROP SEQUENCE MENU_SEQ;

CREATE SEQUENCE MENU_SEQ
NOMAXVALUE 
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO MENU (MENU_ID,MENU_NAME,MENU_RESUME,MENU_STATUS,MENU_PRICE) 
VALUES ('M00001','RED_FOOD','HAPPY NEW YEAR','1','8888');

INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_RESUME,MENU_STATUS,MENU_PRICE)
VALUES('M10002','大富豪盆菜','全新年菜佳餚「大富豪盆菜」（售價$16,800元）。傳統的盆菜據傳源自南宋末年，已有數百年的歷史，是廣東、廣州、深圳和香港新界的漢族飲食習俗，代表「闔家團圓」之意。主廚特別選用八頭鮑魚、金蠔、烏參、瑤柱、蘿蔔、白菜、花菇、鴨、雞、蓮藕和油浸筍殼魚，先將所有食材分開滷好備用，再以白菜為底，層層將食材擺上，最後淋上勾芡的雞高湯，味道馥郁而香濃。',0,16800);
INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_RESUME,MENU_STATUS,MENU_PRICE)
VALUES('M10003','故宮晶華圍爐宴','「故宮晶華圍爐宴」（售價$6,888元），結合6道精緻開胃前菜、2道主菜和1盅故宮御品佛跳牆，相當澎湃美味。另有推出以5款珍稀食材入饌的「五福臨門金元寶」手工水餃，還有「白玉鳳眼」和「乾坤燒蹄」2款阿舍宴的經典菜色。',0,6888);
INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_RESUME,MENU_STATUS,MENU_PRICE)
VALUES('M10004','花開富貴團圓宴','「花開富貴團圓宴」外帶年菜。不僅有集結8道佳餚的「花開富貴團圓宴－圍爐外帶年菜套餐」（6人份），每套售價$8,888元；更獨家推出限量的「土雞瑤柱燉排翅」和古法秘製的「老雞上湯佛跳牆」。',0,8888);

INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_RESUME,MENU_STATUS,MENU_PRICE)
VALUES('M10005','配備燒肉管家的「頂級和牛派對」，價位從6人份、30000元，內含食材有總計1.5公斤的澳洲9+等級和牛四部位（劍心牛舌200g、紐約客牛排300g、戰斧牛排700g、橫膈模300g），手工和牛漢堡、西班牙伊比利豬最高等級Bellota梅花部位400g、6尾澎湖大明蝦、一支軟絲。',0,30000);



--INSERT INTO MENU(MENU_ID,MENU_NAME,MENU_RESUME,MENU_STATUS,MENU_PRICE)
--VALUES('M'||LPAD((MENU_SEQ.NEXTVAL),5,'0'),'花開富貴團圓宴','「花開富貴團圓宴」外帶年菜。不僅有集結8道佳餚的「花開富貴團圓宴－圍爐外帶年菜套餐」（6人份），每套售價$8,888元；更獨家推出限量的「土雞瑤柱燉排翅」和古法秘製的「老雞上湯佛跳牆」。',0,8888);
---------------------------------------------------------------------------------------------------------------------------------
--建立表格:嚴選套餐訂單--
CREATE TABLE MENU_ORDER(
 MENU_OD_ID		          VARCHAR2(6)     NOT NULL,
 MENU_OD_STATUS		      NUMBER(1)       NOT NULL,
 MENU_OD_START		      TIMESTAMP       NOT NULL,
 MENU_OD_BOOK		      TIMESTAMP       NOT NULL,
 MENU_OD_END			  DATE,
 MENU_OD_RATE		      NUMBER(1),
 MENU_OD_MSG		      VARCHAR2(300),
 CUST_ID			      VARCHAR2(6)     NOT NULL,
 CHEF_ID			      VARCHAR2(6)     NOT NULL,
 MENU_ID			      VARCHAR2(6)     NOT NULL,
 CONSTRAINT MENU_ORDER_FK_CUST FOREIGN KEY (CUST_ID) REFERENCES CUST (CUST_ID),
 CONSTRAINT MENU_ORDER_FK_CHEF FOREIGN KEY (CHEF_ID) REFERENCES CHEF (CHEF_ID),
 CONSTRAINT MENU_ORDER_FK_MENU FOREIGN KEY (MENU_ID) REFERENCES MENU (MENU_ID),
 PRIMARY KEY(MENU_OD_ID)
);

INSERT INTO MENU_ORDER (MENU_OD_ID,MENU_OD_STATUS,MENU_OD_START,MENU_OD_BOOK,CUST_ID,CHEF_ID,MENU_ID)
VALUES ('M00001',1,TO_TIMESTAMP('2019-02-12 09:11:12','YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2019-02-25 12:00:00','YYYY-MM-DD HH24:MI:SS'),'T00001','T00002','M00001');
---------------------------------------------------------------
--建立表格:套餐菜色--
CREATE TABLE MENU_DISH(
 MENU_ID		           VARCHAR2(6)     NOT NULL,	
 DISH_ID		           VARCHAR2(6)     NOT NULL,
 CONSTRAINT MENU_DISH_FK1 FOREIGN KEY (MENU_ID) REFERENCES MENU (MENU_ID),
 CONSTRAINT MENU_DISH_FK2 FOREIGN KEY (DISH_ID) REFERENCES DISH (DISH_ID),
 CONSTRAINT MENU_DISH_PK  PRIMARY KEY(MENU_ID,DISH_ID)
);

-----------------------------------------------------------------
--建立表格:員工--
CREATE TABLE EMP(
 EMP_ID		               VARCHAR2(6)      NOT NULL,
 EMP_ACC		           VARCHAR2(15)     NOT NULL,
 EMP_PWD		           VARCHAR2(15)     NOT NULL,
 EMP_NAME	               VARCHAR2(30)     NOT NULL,
 EMP_PIC		           BLOB             NOT NULL,
 PRIMARY KEY (EMP_ID)
);
REM INSERTING into EMP
SET DEFINE OFF;
Insert into EMP (EMP_ID,EMP_ACC,EMP_PWD,EMP_NAME,EMP_PIC) values ('E00001','emp1','123456','boss',hextoraw('453d7a34'));
Insert into EMP (EMP_ID,EMP_ACC,EMP_PWD,EMP_NAME,EMP_PIC) values ('E00002','emp2','123456','bill',hextoraw('453d7a34'));
Insert into EMP (EMP_ID,EMP_ACC,EMP_PWD,EMP_NAME,EMP_PIC) values ('E00003','emp3','123456','cindy',hextoraw('453d7a34'));
-------------------------------------------------------------------
--建立表格:功能--
CREATE TABLE FUN(
 FUN_ID		              VARCHAR2(6)      NOT NULL,		
 FUN_NAME	              VARCHAR2(30)     NOT NULL,	
 PRIMARY KEY (FUN_ID)
);
REM INSERTING into FUN
SET DEFINE OFF;
Insert into FUN (FUN_ID,FUN_NAME) values ('FU0001','廣告管理');
Insert into FUN (FUN_ID,FUN_NAME) values ('FU0002','菜色管理');
Insert into FUN (FUN_ID,FUN_NAME) values ('FU0003','合作廠商管理');
Insert into FUN (FUN_ID,FUN_NAME) values ('FU0004','顧客資料管理');

-------------------------------------------------------------------------
--建立表格:權限--
CREATE TABLE AUTH(
 EMP_ID		             VARCHAR2(6)      NOT NULL,
 FUN_ID		             VARCHAR2(6)      NOT NULL,
 CONSTRAINT AUTH_FK1 FOREIGN KEY (EMP_ID) REFERENCES EMP (EMP_ID),
 CONSTRAINT AUTH_FK2 FOREIGN KEY (FUN_ID) REFERENCES FUN (FUN_ID),
 CONSTRAINT AUTH_PK  PRIMARY KEY (EMP_ID,FUN_ID)
);
REM INSERTING into AUTH
SET DEFINE OFF;
Insert into AUTH (EMP_ID,FUN_ID) values ('E00001','FUN001');

-------------------------------------------------------------------------
--建立表格:主廚論壇文章--
CREATE TABLE FORUM_ART(
 FORUM_ART_ID		        NUMBER(5)      NOT NULL,
 FORUM_ART_NAME		        VARCHAR2(90)   NOT NULL,
 FORUM_ART_CON		        CLOB           NOT NULL,  
 FORUM_ART_START		    TIMESTAMP      NOT NULL,
 FORUM_ART_PIC		        BLOB           NOT NULL,
 FORUM_ART_STATUS	        NUMBER(1)      NOT NULL,
 CHEF_ID			        VARCHAR2(6)    NOT NULL,
 CONSTRAINT FORUM_ART_FK FOREIGN KEY (CHEF_ID) REFERENCES CHEF (CHEF_ID),
 PRIMARY KEY (FORUM_ART_ID)
);


---------------------------------------------------------------------------
--建立表格:主廚論壇留言--
CREATE TABLE FORUM_MSG(
 FORUM_MSG_ID		      NUMBER(5)     NOT NULL,
 FORUM_MSG_CON		      CLOB          NOT NULL,
 FORUM_MSG_START		  TIMESTAMP     NOT NULL,
 FORUM_MSG_STATUS		  NUMBER(1)     NOT NULL,
 FORUM_ART_ID		      NUMBER(5)     NOT NULL,
 CUST_ID			      VARCHAR2(6)   NOT NULL,
 CONSTRAINT FORUM_MSG_FK1 FOREIGN KEY (FORUM_ART_ID) REFERENCES FORUM_ART (FORUM_ART_ID), 
 CONSTRAINT FORUM_MSG_FK2 FOREIGN KEY (CUST_ID)      REFERENCES CUST (CUST_ID),
 PRIMARY KEY (FORUM_MSG_ID)
);

------------------------------------------------------------------------------------
--建立表格:檢舉--
CREATE TABLE REPORT(
 REPORT_ID		          NUMBER(5)      NOT NULL,
 REPORT_TITLE  	          VARCHAR2(30)   NOT NULL,
 REPORT_SORT		      VARCHAR2(30)   NOT NULL,
 REPORT_START		      TIMESTAMP      NOT NULL,
 REPORT_ID_STATUS	      NUMBER(1)      NOT NULL,
 REPORT_CON		          VARCHAR2(100)  NOT NULL,
 CUST_ID		          VARCHAR2(6)    NOT NULL,
 FORUM_ART_ID		      NUMBER(5)      NOT NULL,
 CONSTRAINT REPORT_FK1 FOREIGN KEY (CUST_ID)      REFERENCES CUST (CUST_ID),
 CONSTRAINT REPORT_FK2 FOREIGN KEY (FORUM_ART_ID) REFERENCES FORUM_ART (FORUM_ART_ID),
 PRIMARY KEY(REPORT_ID)
);

-----------------------------------------------------------------
--建立表格:推播通知--
CREATE TABLE BROADCAST(
 BROADCAST_ID		          VARCHAR2(6)    NOT NULL,	
 BROADCAST_START		      TIMESTAMP,
 BROADCAST_CON		          VARCHAR2(100),
 BROADCAST_STATUS		      VARCHAR2(2)    NOT NULL,  
 CUST_ID		              VARCHAR2(6)    NOT NULL,
 CONSTRAINT BROADCAST_FK FOREIGN KEY (CUST_ID) REFERENCES CUST (CUST_ID),
 PRIMARY KEY(BROADCAST_ID)
);


CREATE SEQUENCE BROADCAST_SEQ
NOMAXVALUE 
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO BROADCAST(BROADCAST_ID,BROADCAST_START,BROADCAST_CON,BROADCAST_STATUS,CUST_ID) 
VALUES('B10001',SYSDATE,'NO1:訂單推撥通知',0,'a00001');
INSERT INTO BROADCAST(BROADCAST_ID,BROADCAST_START,BROADCAST_CON,BROADCAST_STATUS,CUST_ID) 
VALUES('B10002',SYSDATE,'NO2:訂單推撥通知',0,'a00002');
INSERT INTO BROADCAST(BROADCAST_ID,BROADCAST_START,BROADCAST_CON,BROADCAST_STATUS,CUST_ID) 
VALUES('B10003',SYSDATE,'NO3:訂單推撥通知',0,'a00003');

INSERT INTO BROADCAST(BROADCAST_ID,BROADCAST_START,BROADCAST_CON,BROADCAST_STATUS,CUST_ID) 
VALUES('B'||LPAD((BROADCAST_SEQ.NEXTVAL),5,'0'),SYSDATE,'NO1:訂單推撥通知',0,'a00001');
----------------------------------------------------------------------------------------------------------------------------------


-----------------------食神嚴選食材訂單自動編號器-------------------------------
CREATE SEQUENCE FOOD_ORDER_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
-----------------------------------------------------------------

-----------------------食材供應商1資料----------------------------------
INSERT INTO CUST (CUST_ID, CUST_ACC, CUST_PWD, CUST_NAME, CUST_SEX, CUST_TEL, 
CUST_ADDR, CUST_PID, CUST_MAIL, CUST_BRD, CUST_REG, CUST_STATUS, CUST_NINAME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.NEXTVAL), 5, '0'), 'ABC', '123', '周子怡', 'f', '0958111222' , '桃園市大園區橫峰里中山南路二段246號', 'B224448640', '123@gmail.com', 
to_date('1988/11/21', 'YYYY/MM/DD'), to_date('2018/02/06', 'YYYY/MM/DD'), 'c0', '怡姐');

INSERT INTO FOOD_SUP(FOOD_SUP_ID, FOOD_SUP_NAME, FOOD_SUP_TEL, FOOD_SUP_STATUS, FOOD_SUP_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), '宏昇畜牧場', '03-1234567', 's1',
'宏昇畜牧場建立於民國六十五年以養白蛋雞為主。三十幾年養雞技術和一流的好口碑傳聞於北中南部地區。民國九十三宏昇轉型機能安全健康的生鮮雞蛋！主要生產德國羅曼褐色雞生褐蛋和烏骨雞生青蛋。因近幾年台灣的食安風暴凸顯食品安全重要性。');

INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00009', '洗選蛋', 'p3', 65, '10顆入', '臺灣', 
'洗選分級，個個精挑，粒粒細選');


-----------------------食材供應商2資料----------------------------------
INSERT INTO CUST (CUST_ID, CUST_ACC, CUST_PWD, CUST_NAME, CUST_SEX, CUST_TEL, 
CUST_ADDR, CUST_PID, CUST_MAIL, CUST_BRD, CUST_REG, CUST_STATUS, CUST_NINAME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.NEXTVAL), 5, '0'), 'fg1', '123', '蘇鵬', 'm', '0958111222', '屏東市中華路166號1樓', 'T150500669', '456@gmail.com', 
to_date('1980/05/21', 'YYYY/MM/DD'), to_date('2018/02/07', 'YYYY/MM/DD'), 'c0', 'Lion');

INSERT INTO FOOD_SUP(FOOD_SUP_ID, FOOD_SUP_NAME, FOOD_SUP_TEL, FOOD_SUP_STATUS, FOOD_SUP_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), '中央畜產有限公司', '08-7217729', 's0',
'中央畜產牧場創立於民國六十八年，由蘇氏兄弟共同規劃經營，座落於美麗的田野間，屏東縣麟洛鄉新田村，位於南二高南下 404KL 大武山下，牧場面積約8公頃。');

-----------------------食材供應商3資料----------------------------------
INSERT INTO CUST (CUST_ID, CUST_ACC, CUST_PWD, CUST_NAME, CUST_SEX, CUST_TEL, 
CUST_ADDR, CUST_PID, CUST_MAIL, CUST_BRD, CUST_REG, CUST_STATUS, CUST_NINAME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.NEXTVAL), 5, '0'), 'ccc', '123', '張靖男', 'm', '0958111222', '台中市北屯區松竹路二段258號', 'L103239021', 'nnn@gmail.com', 
to_date('1977/06/01', 'YYYY/MM/DD'), to_date('2018/02/08', 'YYYY/MM/DD'), 'c0', '阿男');

INSERT INTO FOOD_SUP(FOOD_SUP_ID, FOOD_SUP_NAME, FOOD_SUP_TEL, FOOD_SUP_STATUS, FOOD_SUP_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), '翠軒', '04-6817729', 's1',
'台糖公司畜殖事業部所生產之豬肉肉品，由於絕無藥物殘留，也絕不使用瘦肉精，而且衛生美味，早
已有口皆碑。但因隸屬公營企業，較不擅於行銷，故有許多消費者屢屢抱怨：「明知台糖肉品好，卻
不知何處買得到？」。');

INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00016', '五花肉', 'p4', 369, '1kg', '臺灣', 
'因為肥瘦層層相間，故又稱為「三層肉」；也因為油脂與瘦肉層疊分佈，具有多汁性、肉質較軟嫩的特性，口感甘甜、非常鮮嫩美味，很棒！');

INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00015', '黃金松阪豬肉', 'p4', 350, '300g', '臺灣', 
'豬頸肉，位於豬的頸部兩側，是最珍稀的豬肉部位，在台灣有人吃了之後發現，它的口感與日本的松阪牛肉很像，因此又稱它為松阪豬肉。一隻豬只有左右兩片，因為數量少，因此價位比較高');
-----------------------食材供應商4資料----------------------------------
INSERT INTO CUST (CUST_ID, CUST_ACC, CUST_PWD, CUST_NAME, CUST_SEX, CUST_TEL, 
CUST_ADDR, CUST_PID, CUST_MAIL, CUST_BRD, CUST_REG, CUST_STATUS, CUST_NINAME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.NEXTVAL), 5, '0'), 'RT5G', '658W', '駒場一郎', 'm', '0952115123', '嘉義市西區北港路310號', 'A140818041', 'dd7@gmail.com', 
to_date('1980/06/01', 'YYYY/MM/DD'), to_date('2018/05/08', 'YYYY/MM/DD'), 'c0', '一郎');

INSERT INTO FOOD_SUP(FOOD_SUP_ID, FOOD_SUP_NAME, FOOD_SUP_TEL, FOOD_SUP_STATUS, FOOD_SUP_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), '蝦夷農產', '05-1509436', 's1', '專門從日本進口高級食材');


INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00025', '翼板牛排', 'p4', 320, '150g', '日本', 
'去除肩峰部分,頸側,肉不厚的部分後整形，全體有均一的(脂肪)紋路肉質');

INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00024', '牛頸肉', 'p4', 349, '100g', '日本', 
'A5冷藏和牛/頂級松阪牛因為經常活動，脂肪較少，屬於較硬的瘦肉，適合用來燉煮湯品。');

INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00023', '牛舌', 'p0', 300, '250g', '日本', 
'獨家純手工精修牛舌片
適合炙烤的黃金比例厚度
豐富油脂入口即化更勝草飼牛');

INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00022', '牛頰', 'p2', 600, '1kg', '日本', 
'不管是要做紅酒燉牛頰還是蔬菜比較多的蔬菜燉牛頰都很適合!');

-----------------------食材供應商5資料----------------------------------
INSERT INTO CUST (CUST_ID, CUST_ACC, CUST_PWD, CUST_NAME, CUST_SEX, CUST_TEL, 
CUST_ADDR, CUST_PID, CUST_MAIL, CUST_BRD, CUST_REG, CUST_STATUS, CUST_NINAME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.NEXTVAL), 5, '0'), 'FERw3', 'tgr55', '稻田多摩子', 'f', '0952115123', '嘉義市西區北港路310號', 'A140818041', 'dd7@gmail.com', 
to_date('1971/08/11', 'YYYY/MM/DD'), to_date('2018/06/18', 'YYYY/MM/DD'), 'c0', '蛋姐');


INSERT INTO FOOD_SUP(FOOD_SUP_ID, FOOD_SUP_NAME, FOOD_SUP_TEL, FOOD_SUP_STATUS, FOOD_SUP_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), '台南農產', '06-4555436','s1', '台灣出產');

INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00016', '五花肉', 'p4', 520, '1kg', '臺灣', 
'油脂與瘦肉層疊分佈，具有多汁性、肉質較軟嫩的特性，口感甘甜、非常鮮嫩美味，很棒！');
INSERT INTO FOOD_MALL(FOOD_SUP_ID, FOOD_ID, FOOD_M_NAME, FOOD_M_STATUS, FOOD_M_PRICE, FOOD_M_UNIT, FOOD_M_PLACE, FOOD_M_RESUME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'), 'F00024', '牛頸肉', 'p4', 310, '100g', '臺灣', 
'因為經常活動，脂肪較少，屬於較硬的瘦肉，適合用來燉煮湯品。');

commit;

-------------------------桑野信介-------------------------------------------------
INSERT INTO CUST (CUST_ID, CUST_ACC, CUST_PWD, CUST_NAME, CUST_SEX, CUST_TEL, 
CUST_ADDR, CUST_PID, CUST_MAIL, CUST_BRD, CUST_REG, CUST_STATUS, CUST_NINAME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.NEXTVAL), 5, '0'), 'N573JHTY', 'AA123DD', '桑野信介', 'm', '0958111222', '台中市龍井區新興路17巷3號', 'L176024587', 'xu5ktleo@gmail.com', 
to_date('1966/07/04', 'YYYY/MM/DD'), to_date('2018/10/10', 'YYYY/MM/DD'), 'c0', '信介');
--------------------------食神嚴選食材訂單資料---------------------
INSERT INTO FOOD_ORDER (FOOD_OR_ID, FOOD_OR_STATUS, FOOD_OR_START, FOOD_OR_SEND, FOOD_OR_RCV, FOOD_OR_END, FOOD_OR_NAME, FOOD_OR_ADDR, FOOD_OR_TEL, CUST_ID)
VALUES ('FO'||'20181121'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.NEXTVAL), 6, '0'), 'o4', TO_DATE('2018/11/21', 'YYYY/MM/DD'), TO_DATE('2018/11/23' , 'YYYY/MM/DD'),
TO_DATE('2018/11/24' , 'YYYY/MM/DD'),TO_DATE('2018/11/25' , 'YYYY/MM/DD'), '桑野信介', '台中市龍井區新興路17巷3號', '0958111222', 'C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'));

INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL, FOOD_OD_RATE, FOOD_OD_MSG)
VALUES ('FO'||'20181121'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00004', 'F00024', 2, 698, 4, '相當新鮮, 非常推薦');
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL, FOOD_OD_RATE, FOOD_OD_MSG)
VALUES ('FO'||'20181121'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00001', 'F00009', 2, 130, 3, '尚可');

INSERT INTO FOOD_ORDER (FOOD_OR_ID, FOOD_OR_STATUS, FOOD_OR_START, FOOD_OR_SEND, FOOD_OR_RCV, FOOD_OR_END, FOOD_OR_NAME, FOOD_OR_ADDR, FOOD_OR_TEL, CUST_ID)
VALUES ('FO'||'20181124'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.NEXTVAL), 6, '0'), 'o4', TO_DATE('2018/11/24', 'YYYY/MM/DD'), TO_DATE('2018/11/27' , 'YYYY/MM/DD'),
TO_DATE('2018/11/28' , 'YYYY/MM/DD'),TO_DATE('2018/11/29' , 'YYYY/MM/DD'), '桑野信介', '台中市龍井區新興路17巷3號', '0958111222', 'C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'));

INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL, FOOD_OD_RATE, FOOD_OD_MSG)
VALUES ('FO'||'20181124'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00004', 'F00025', 2, 640, 5, '色澤好看');
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL, FOOD_OD_RATE, FOOD_OD_MSG)
VALUES ('FO'||'20181124'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00004', 'F00024', 1, 698, 4, '依舊保持高水準');
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20181124'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00001', 'F00009', 1, 65);
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL, FOOD_OD_RATE)
VALUES ('FO'||'20181124'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00003', 'F00016', 2, 700, 3);

---------------------------李舜生-------------------------------
INSERT INTO CUST (CUST_ID, CUST_ACC, CUST_PWD, CUST_NAME, CUST_SEX, CUST_TEL, 
CUST_ADDR, CUST_PID, CUST_MAIL, CUST_BRD, CUST_REG, CUST_STATUS, CUST_NINAME)
VALUES ('C'||LPAD(TO_CHAR (CUST_SEQ.NEXTVAL), 5, '0'), 'Dw4hg1', '1qaz2wsx', '李舜生', 'm', '0958021852', '桃園市復興區澤仁里中山路8號', 'H151941450', '555@gmail.com', 
to_date('1986/07/04', 'YYYY/MM/DD'), to_date('2018/11/01', 'YYYY/MM/DD'), 'c0', '黑');
--------------------------食神嚴選食材訂單資料---------------------

INSERT INTO FOOD_ORDER (FOOD_OR_ID, FOOD_OR_STATUS, FOOD_OR_START, FOOD_OR_SEND, FOOD_OR_RCV ,FOOD_OR_NAME, FOOD_OR_ADDR, FOOD_OR_TEL, CUST_ID)
VALUES ('FO'||'20190130'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.NEXTVAL), 6, '0'), 'o3', TO_DATE('2019/01/30', 'YYYY/MM/DD'), TO_DATE('2019/02/01' , 'YYYY/MM/DD'), TO_DATE('2019/02/02' , 'YYYY/MM/DD') , '李舜生', '桃園市復興區澤仁里中山路8號', '0958021852', 'C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'));
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190130'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00005', 'F00016', 1, 520);

INSERT INTO FOOD_ORDER (FOOD_OR_ID, FOOD_OR_STATUS, FOOD_OR_START, FOOD_OR_SEND, FOOD_OR_NAME, FOOD_OR_ADDR, FOOD_OR_TEL, CUST_ID)
VALUES ('FO'||'20190208'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.NEXTVAL), 6, '0'), 'o2', TO_DATE('2019/02/08', 'YYYY/MM/DD'), TO_DATE('2019/02/12' , 'YYYY/MM/DD'), '李舜生', '桃園市復興區澤仁里中山路8號', '0958021852', 'C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'));
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190208'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00001', 'F00009', 1, 65);
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190208'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00005', 'F00024', 2, 620);
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190208'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00004', 'F00024', 2, 349);

INSERT INTO FOOD_ORDER (FOOD_OR_ID, FOOD_OR_STATUS, FOOD_OR_START, FOOD_OR_SEND, FOOD_OR_NAME, FOOD_OR_ADDR, FOOD_OR_TEL, CUST_ID)
VALUES ('FO'||'20190211'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.NEXTVAL), 6, '0'), 'o1', TO_DATE('2019/02/11', 'YYYY/MM/DD'), TO_DATE('2019/02/16' , 'YYYY/MM/DD'), '李舜生', '桃園市復興區澤仁里中山路8號', '0958021852', 'C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'));
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190211'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00005', 'F00016', 2, 1040);
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190211'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00001', 'F00009', 1, 65);


INSERT INTO FOOD_ORDER (FOOD_OR_ID, FOOD_OR_STATUS, FOOD_OR_START, FOOD_OR_SEND, FOOD_OR_NAME, FOOD_OR_ADDR, FOOD_OR_TEL, CUST_ID)
VALUES ('FO'||'20190215'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.NEXTVAL), 6, '0'), 'o0', TO_DATE('2019/02/15', 'YYYY/MM/DD'), TO_DATE('2019/02/20' , 'YYYY/MM/DD'), '李舜生', '桃園市復興區澤仁里中山路8號', '0958021852', 'C'||LPAD(TO_CHAR (CUST_SEQ.CURRVAL), 5, '0'));
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190215'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00004', 'F00025', 2, 640);
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190215'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00003', 'F00016', 1, 369);
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190215'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00001', 'F00009', 4, 260);
INSERT INTO FOOD_OR_DETAIL (FOOD_OR_ID, FOOD_SUP_ID, FOOD_ID, FOOD_OD_QTY, FOOD_OD_STOTAL)
VALUES ('FO'||'20190215'||'-'||LPAD(TO_CHAR(FOOD_ORDER_SEQ.CURRVAL), 6, '0'), 'C00003', 'F00015', 10, 3500);


commit;